openapi: 3.0.0
info:
  title: Word Service
  description: A simple service that allows a GET operation
  version: 0.0.1
servers: 
  - url: http://localhost:8080
    description: Local dev server
    
paths:
  /word:

    get:
      summary: Retrieves a random word and definition
      parameters: 
        - name: word
          in: path
          required: true
          description: pulls random word and definition
          schema:
            type: string
            format: string
      responses:
        '200':
          description: random word
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Word'
                
components:
  schemas:
    Word:
      properties:
        word:
          type: string
        definition:
          type: string