openapi: 3.0.0
info:
  title: Quote Service
  description: A simple service that allows a GET operation
  version: 0.0.1
servers: 
  - url: http://localhost:8080
    description: Local dev server
    
paths:
  /quote:

    get:
      summary: Retrieves a random entry for the quote
      parameters: 
        - name: quote
          in: path
          required: true
          description: pulls random quote
          schema:
            type: string
            format: string
      responses:
        '200':
          description: random quote
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Name'
                
components:
  schemas:
    Name:
      properties:
        author:
          type: string
        quote:
          type: string