openapi: 3.0.0
info:
  title: Magic Eightball Service
  description: A simple service that allows a post
  version: 0.0.1
servers: 
  - url: http://localhost:8080
    description: Local dev server
    
paths:
  /magic:
    post:
      summary: Creates a new question entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MagicEight'
      responses:
        '201':
          description: Returns an answer
          content:
            application/json:
              schema:

                $ref: '#/components/schemas/MagicEight'
              
          
          
components:
  schemas:
    MagicEight:
      properties:
        question:
          type: string
        answer:
          type: string
      